### DELETE with Authorization
DELETE http://localhost:5003/catalog/1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjFlRFkwRjNwSm4yWW0zaFphdE1PWSJ9.eyJpc3MiOiJodHRwczovL2Rldi16Y3pkeWxkcTRubGQzN2Q3LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJpTVVXWkxLenJFSUM4MDNXQmRpUjYya2pMZkFLRGo2RkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9mbHlpbmctZGVlciIsImlhdCI6MTc2MzQ5Nzk4NywiZXhwIjoxNzYzNTg0Mzg3LCJzY29wZSI6ImRlbGV0ZTpjYXRhbG9nIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiaU1VV1pMS3pyRUlDODAzV0JkaVI2MmtqTGZBS0RqNkYifQ.ehYLSDU209kO_ROJc6-rQRVdzUjKAKITYD8GC75hWPj8fFTx2Ih-nBp0j_q7Kld8i6lCI1UXVNM9CUN_VZP9dJOawTUIRmMhjimsi73RbZlCFMYuH7fg_Y8eI77MDi1t-v_-e01o6zvEqI7Bnw7zzWkgvDUDv8jfJ1mrE7BwAJhjdVXIceV5Kne7mGqfN5hL_m8pMi9dlcqmeOD_4o_JBV-ieelxysoD9Vv_b5d6sJIJEC6w0Mfm8HSmI7hDoi-YziIwWND0HnOdflTyspBelU0gz5g9QrRogxtGdZbU7k75NFdlGx_8xmKsQIUmRDFhlfs4Y-MqvXlQeEZ2Wq85ew